CREATE DATABASE VENDAS_DE_CARRO;
USE VENDAS_DE_CARRO;

CREATE TABLE CLIENTE (

	 id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR (100) NOT NULL,
    endereco TEXT NOT NULL,
    telefone VARCHAR (15) NOT NULL,
    email VARCHAR (100) NOT NULL
    );

CREATE TABLE CARROS(
	ID INT auto_increment PRIMARY KEY,
    MARCA VARCHAR (50) NOT NULL,
    MODELO varchar (50) NOT NULL,
    ANO INT NOT NULL,
    COR VARCHAR (30) NOT NULL,
    CHASSI VARCHAR (30) UNIQUE NOT NULL,
    PRECO DECIMAL (10,2) NOT NULL,
    STATUS ENUM('EM ESTOQUE', 'VENDIDO') NOT NULL
    );
    
    CREATE TABLE VENDAS (
		ID INT AUTO_INCREMENT PRIMARY KEY,
        CLENTES_ID  INT NOT NULL,
        CARROS_ID INT NOT NULL,
        VENDEDOR_ID INT NOT NULL,
        DATA DATE NOT NULL,
        VALOR DECIMAL (10,2) NOT NULL,
        COMISSAO DECIMAL (10,2) NOT NULL,
        FOREIGN KEY (CLIENTES_ID) REFERENCES CLIENTES (ID),
        FOREIGN KEY (CARROS_ID) REFERENCES CARROS (ID),
        FOREIGN KEY (VENDEDOR_ID) REFERENCES  VENDEDORRES (ID)
        );
        
	CREATE TABLE VENDEDORES (
        ID INT AUTO_INCREMENT PRIMARY KEY,
        NOME VARCHAR (100) NOT NULL,
        CPF VARCHAR (14) UNIQUE NOT NULL,
        TELEFONE VARCHAR (15) NOT NULL,
        EMAIL VARCHAR (100) UNIQUE NOT NULL
        );
        
	CREATE TABLE FORNECEDORES (
			ID INT AUTO_INCREMENT PRIMARY KEY,
            NOME_EMPRESA VARCHAR (100) NOT NULL,
            CNPJ VARCHAR (18) UNIQUE NOT NULL,
            CONTATO VARCHAR (50) NOT NULL
            );
            
	CREATE TABLE PAGAMENTOS_FORNECEDORES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FORNECEDORES_ID INT NOT NULL,
    DATA DATE NOT NULL,
    VALOR DECIMAL(10 , 2 ) NOT NULL,
    DESCRICAO TEXT,
    FOREIGN KEY (FORNECEDOR_ID)
        REFERENCES FORNECEDORES (ID)
);
            
            
            
            
            
    